if(EXISTS "/home/charlie/dev/spira/build-debug/unit_tests[1]_tests.cmake")
  include("/home/charlie/dev/spira/build-debug/unit_tests[1]_tests.cmake")
else()
  add_test(unit_tests_NOT_BUILT unit_tests_NOT_BUILT)
endif()
